dubbo:
  config-center:
    address: zookeeper://zk01.soa.internal.weimobdev.com:2181
  registry:
    address: zookeeper://zk01.soa.internal.weimobdev.com:2181
    check: false
  protocol:
    name: dubbo
  application:
    name: dubbo-consumer


