spring:
  application:
    name: dubbo-provider

dubbo:
  config-center:
    address: nacos://127.0.0.1:8848
    app-name: dubbo-provider
  scan:
    base-packages: com.xh.demo.dubbo
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 3000
